# Generated by Django 3.2.25 on 2024-05-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('lost_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=250)),
                ('user_picture', models.ImageField(upload_to='upload/image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('picture_of_item', models.ImageField(upload_to='upload/image')),
                ('address', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profileapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField(unique=True)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profileapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.user')),
            ],
        ),
    ]
