# Generated by Django 3.2.25 on 2024-05-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture_of_item',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_picture',
        ),
    ]
