# Generated by Django 3.2.25 on 2024-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20240523_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='picture_of_item',
            field=models.ImageField(default='default.jpg', upload_to='item_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(default='default.jpg', upload_to='user_pictures/'),
        ),
    ]
